@startuml
class XfForm {
    refresh()
}
class BoundElement{
    ref
    evalBinding()
    getBindingExpr()
    getModel()
}
package "model" #DDDDDD {
    class XfModel{
        bindingMap[]
        rebuild()
        recalculate()
        revalidate()
        registerBinding()
    }
    class XfInstance{
        getInstanceData()
        getDefaultContext()
    }

    class ModelItem{
        node
        getValue
        setValue
        readonly
        required
        relevant
        valid
        type
    }

    class XfBind
    class XfSubmission


}

XfBind o-- ModelItem

package "view" #DDDDDD{
    class UIElement{
        refresh()
    }
    abstract class AbstractControl{
        getValue()
    }
    class XfSwitch #lightgrey
    class XfSelect1 #lightgrey
    class XfSelect #lightgrey
    UIElement <|-- AbstractControl
    AbstractControl <|-- XfInput
    AbstractControl <|-- XfOutput
    AbstractControl <|-- XfButton
    UIElement <|-- XfRepeat
    UIElement <|-- XfRepeatitem
    UIElement <|-- XfGroup
    UIElement <|-- XfSwitch
    AbstractControl <|-- XfSelect
    AbstractControl <|-- XfSelect1
}

package "controller" #DDDDDD{
    class XfAction{
        needsRebuild
        needsRecalculate
        needsRevalidate
        needsRefresh
        execute()
        actionPerformed()
    }
    XfAction <|-- XfDelete
    XfAction <|-- XfAppend
    XfAction <|-- XfInsert
    XfAction <|-- XfSetvalue

}



BoundElement <|-- UIElement
BoundElement <|-- XfAction
BoundElement <|-- XfBind
BoundElement <|-- XfSubmission





@enduml
