@startuml
class XfForm {
    init()
    refresh()
}
class ModelItem{
    node
    getValue
    setValue
    readonly
    required
    relevant
    valid
    type
}
class ForeElement{
    model
    abstract evalInContext()
    isBound()
    isNotBound()
    _inScopeContext()
}

class BoundElement{
    ref
    evalInContext()
    init(model)
    getBindingExpr()
    getModelItem()

}

ForeElement <|-- BoundElement


package "model" #DDDDDD {
    class XfModel{
        bindingMap[]
        rebuild()
        recalculate()
        revalidate()
        registerBinding()
    }
    ForeElement <-- XfModel
    class XfInstance{
        getInstanceData()
        getDefaultContext()
    }
    ForeElement <-- XfInstance
    class XfBind
    class XfSubmission
}



package "view" #DDDDDD{
    class UIElement{
        refresh()
    }
    abstract class AbstractControl{
        getValue()
    }
    class XfSwitch #lightgrey
    class XfSelect1 #lightgrey
    class XfSelect #lightgrey
    BoundElement <|-- AbstractControl
    AbstractControl <|-- XfInput
    AbstractControl <|-- XfOutput
    AbstractControl <|-- XfButton
    BoundElement <|-- XfRepeat
    BoundElement <|-- XfRepeatitem
    BoundElement <|-- XfGroup
    BoundElement <|-- XfSwitch
    AbstractControl <|-- XfSelect
    AbstractControl <|-- XfSelect1
}

package "controller" #DDDDDD{
    class XfAction{
        needsRebuild
        needsRecalculate
        needsRevalidate
        needsRefresh
        execute()
        actionPerformed()
    }
    XfAction <|-- XfDelete
    XfAction <|-- XfAppend
    XfAction <|-- XfInsert
    XfAction <|-- XfSetvalue

}



BoundElement <|-- XfAction
ForeElement <|-- XfBind
BoundElement <|-- XfSubmission



@enduml
