@startuml
Title: updates from client

(*)  --> "update.xql"
note right
- get changes from request
- get instances from session
end note

--> "fore:update($changes,$instances)"



If "input is verbose" then
--> [Yes] "turn on verbosity"
--> "run command"
else
--> "run command"
Endif
-->(*)
@enduml